const ACTION_ENUMS = {
    DATA_VISUAL_STATE_RESTORE_DATA: 'DATA_VISUAL_STATE_RESTORE_DATA',
    SETTINGS_STATE_SET_END_SORTING: 'SETTINGS_STATE_SET_END_SORTING',
    SETTINGS_STATE_SET_INDEX_SORT: 'SETTINGS_STATE_SET_INDEX_SORT',
    SETTINGS_STATE_SET_SPEED: 'SETTINGS_STATE_SET_SPEED',
    SETTINGS_STATE_SET_MAX_VALUE: 'SETTINGS_STATE_SET_MAX_VALUE',
    SETTINGS_STATE_SET_MAX_ARRAY: 'SETTINGS_STATE_SET_MAX_ARRAY',
    SETTINGS_STATE_SET_RUN_SORTING: 'SETTINGS_STATE_SET_RUN_SORTING',
    SETTINGS_STATE_SET_START_SORTING: 'SETTINGS_STATE_SET_START_SORTING',
    
    SORT_STATE_SET_IS_SELECTED: 'SORT_STATE_SET_IS_SELECTED',
    SORT_STATE_RESTORE_DATA: 'SORT_STATE_RESTORE_DATA',
};

export default ACTION_ENUMS;
